In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,headline,article
0,EXCLUSIVE: दिल्ली में डीजल टैक्सियों पर बैन से...,दिल्ली में सुप्रीम कोर्ट के डीज़ल टैक्सियों को...
1,जॉर्डन: राष्ट्रपति मुखर्जी ने 86 करोड़ डॉलर के...,जॉर्डन के ऐतिहासिक दौरे पर पहुंचे राष्ट्रपति प...
2,UN में पाकिस्तान की राजदूत मलीहा लोधी ने कराई ...,पाकिस्तानी नेताओं को विवादित और हास्यास्पद बया...
3,38 देशों में पीएम नरेंद्र मोदी बायोपिक को रिली...,पीएम नरेंद्र मोदी बायोपिक में विवेक ओबेरॉय ने ...
4,13 अगस्त 2011: दिनभर की बड़ी खबरें पढ़ें,"देश, दुनिया, महानगर, खेल, आर्थिक और बॉलीवुड मे..."

In [4]:
# Combine headline and content
df["text"] = (
    df["headline"].fillna("") + " " +
    df["article"].fillna("")
)

# Remove extra spaces
df["text"] = (
    df["text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Remove duplicate articles
df = df.drop_duplicates(subset=["text"])

In [5]:
keywords = [
    "जलवायु",
    "मौसम",
    "बारिश",
    "तापमान",
    "गर्मी",
    "ठंड",
    "सूखा",
    "बाढ़",
    "चक्रवात",
    "तूफान",
    "हिमपात",
    "मानसून",
    "ग्लोबल वार्मिंग",
    "पर्यावरण",
    "प्रदूषण",
    "ग्रीनहाउस",
    "कार्बन",
    "समुद्र",
    "समुद्र स्तर",
    "आईएमडी",
    "मौसम विभाग"
]

In [6]:
pattern = "|".join(keywords)

df = df[
    df["text"].str.contains(pattern, case=False, na=False)
]

In [7]:
df[["text"]].to_csv(
    "hindi_mlm_dataset2.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df.shape)

(23284, 3)

In [8]:
df = pd.read_csv("hindi_mlm_dataset2.csv")

In [9]:
df.head(10)

                                                text
0  13 अगस्त 2011: दिनभर की बड़ी खबरें पढ़ें देश, ...
1  चंद्रयान-2 की लॉन्चिंग लाइव देखना है तो यहां क...
2  फैक्ट फाइल: क्या विमान वाकई आकाश से गिराते हैं...
3  पेरिस में आर या पार जब दुनिया के 150 देशों के ...
4  भारत दौरे पर बांग्लादेश के विदेश सचिव, आतंकवाद...
5  अन्‍ना की गिरफ्तारी पर किसने क्‍या कहा... दिल्...
6  एक क्लिक में पढ़ें 30 जुलाई की सभी खबरें 11:52...
7  15 अगस्त को मुंबई में बड़ी रैली करेगी AAP आम आ...
8  लद्दाख को देश से जोड़ने वाला श्रीनगर-लेह राष्ट...
9  छिंदवाड़ा में ओले गिरने से 3 लोगों की मौत, श‍ि...

In [10]:
import pandas as pd

# Load dataset
df = pd.read_csv("bbc_hindi_articles_with_categories_cleaned.csv")
print(df.head())
print(df.columns)

                                            Headline  \
0  बांग्लादेश जमात-ए-इस्लामी और मोदी-बाइडन की बात...
1        भारत में महिलाएं क्यों छिपाती हैं मेनोपॉज़?
2  वीडियो, 'वडोदरा शहर में करोड़ों रुपए के बंगले ...
3  अवनि लेखरा: टोक्यो के बाद पेरिस में भी गोल्ड प...
4  पैरालंपिक में भाग्यश्री जाधव: मेहनत और लगन से ...

                                             Content Category
0  प्रधानमंत्री नरेंद्र मोदी और अमेरिका राष्ट्रपत...     भारत
1  “मेरे पति चाहते थे कि मैं हमेशा तैयार और सज सं...     भारत
2  गुजरात में लगातार हो रही भारी बारिश के कारण कई...     भारत
3  अवनि लेखरा ने पेरिस पैरालंपिक में महिलाओं की 1...     भारत
4  पेरिस पैरालंपिक खेलों की शुरुआत 28 अगस्त से हो...     भारत
Index(['Headline', 'Content', 'Category'], dtype='object')

In [11]:
# Combine headline and content
df["text"] = (
    df["Headline"].fillna("") + " " +
    df["Content"].fillna("")
)

# Remove extra spaces
df["text"] = (
    df["text"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Remove duplicate articles
df = df.drop_duplicates(subset=["text"])

In [12]:
keywords = [
    "जलवायु",
    "मौसम",
    "बारिश",
    "तापमान",
    "गर्मी",
    "ठंड",
    "सूखा",
    "बाढ़",
    "चक्रवात",
    "तूफान",
    "हिमपात",
    "मानसून",
    "ग्लोबल वार्मिंग",
    "पर्यावरण",
    "प्रदूषण",
    "ग्रीनहाउस",
    "कार्बन",
    "समुद्र",
    "समुद्र स्तर",
    "आईएमडी",
    "मौसम विभाग"
]

In [13]:
pattern = "|".join(keywords)

df = df[
    df["text"].str.contains(pattern, case=False, na=False)
]

In [14]:
df[["text"]].to_csv(
    "hindi_mlm_dataset3.csv",
    index=False,
    encoding="utf-8-sig"
)

print(df.shape)

(830, 4)

In [15]:
df = pd.read_csv("hindi_mlm_dataset3.csv")

In [16]:
df.head()

                                                text
0  बांग्लादेश जमात-ए-इस्लामी और मोदी-बाइडन की बात...
1  भारत में महिलाएं क्यों छिपाती हैं मेनोपॉज़? “म...
2  वीडियो, 'वडोदरा शहर में करोड़ों रुपए के बंगले ...
3  चंपाई सोरेन झारखंड में क्या बीजेपी को सत्ता तक...
4  पुतिन को मंगोलिया में किया जाए गिरफ्तार, अंतरर...

In [17]:
dataset1 = pd.read_csv("hindi_mlm_dataset2.csv")
dataset2 = pd.read_csv("hindi_mlm_dataset3.csv")

In [24]:
target_total = 4600 #rows

len1 = len("hindi_mlm_dataset3.csv")
len2 = len("hindi_mlm_dataset2.csv")
total_len = len1 + len2
print(total_len)

n1 = 830
n2 = target_total-n1

sample1 = dataset2.sample(n=n1, random_state=42)
sample2 = dataset1.sample(n=n2, random_state=42)

final_dataset = pd.concat([sample1, sample2], ignore_index=True)

print(final_dataset.head())
print(final_dataset.info())

44
                                                text
0  सूर्य ग्रहण: दिन में चार मिनट तक रहेगा अंधेरा,...
1  भारतीय महिला बैडमिंटन टीम ने यंग ब्रिगेड के सह...
2  नेपाल में बोधिचित्त वृक्षों की चिंता: 'सोने की...
3  आईपीएल के सुपर संडे में कई रिकॉर्ड बने, लेकिन ...
4  भारत ईरान ने मतभेद भुलाकर किया ये अहम समझौता, ...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    4600 non-null   object
dtypes: object(1)
memory usage: 36.1+ KB
None

In [25]:
final_dataset.to_csv(
    "final_dataset_hindi1.csv",
    index=False
)

print(final_dataset.shape)

(4600, 1)

In [26]:
df = pd.read_csv("final_dataset_hindi1.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    4600 non-null   object
dtypes: object(1)
memory usage: 36.1+ KB

In [23]:
df.head()

                                                text
0  उत्तराखंड: भारी बारिश ने मचाई तबाही, 10 की मौत...
1  दक्षिण चीन सागर में अमेरिका ने भेजा युद्धपोत, ...
2  इस हफ्ते शेयर बाजार की चाल पर ये फैक्‍टर करेंग...
3  पंजाबः खुशहाल और समृद्ध सूबा पंजाब के किसान इन...
4  मॉनसून शुरू होते ही सब्जियों ने दिखाए तेवर, भा...